# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Bloody computers!
email: pawel@dunst.me
description: > # this means to ignore newlines until "baseurl:"
  System Admin - Graphic Artist - Linux Enthusiast
baseurl: "/startbootstrap-freelancer-jekyll" # the subpath of your site, e.g. /blog
url: "http://dunst.me" # the base hostname & protocol for your site

# Social media profiles - feel free to add more here
twitter_username: pav0pav
github_username:  pav0pav
facebook_username: StartBootstrap
#instagram_username: beyonce
#stackoverflow_url: https://
#googleplus_username: BobMarley
#skype_username: Pawel D.
#linkedin_url: https://

# Address information
address_street: 3034 Melrose Place
address_city: Beverly Hills
address_state: CA
address_zip: 90201

# Build settings
markdown: kramdown
