# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Bloody computers!
email: pawel@dunst.me
description: > # this means to ignore newlines until "baseurl:"
  Half System Admin - Half IT Ninja - Half Monster
baseurl: "/startbootstrap-freelancer-jekyll" # the subpath of your site, e.g. /blog
url: "http://dunst.me" # the base hostname & protocol for your site

# Social media profiles - feel free to add more here
twitter_username: pav0pav
github_username:  pav0pav
facebook_username: Bloody computers!
#instagram_username: pav0pav
#stackoverflow_url: https://
#googleplus_username: Bloody computers!
#skype_username: Pawel D.
#linkedin_url: https://www.linkedin.com/in/pawel-dunst-64030510b/

# Address information
address_street: 300 Ann Street
address_city: Brisbane
address_state: QLD
address_zip: 4000

# Build settings
markdown: kramdown
